Repository AY2223S2-CS2113-T12-4/tp, pull requests merged in 2023-04, with the labels that each got.

#267 Check `exit` command arguments
  src/main/java/wellnus/command/ExitCommand.java
Labels: type.Bug, priority.Low

#265 Implement data storage/restore for gamification feature
  src/main/java/wellnus/atomichabit/command/UpdateCommand.java
  src/main/java/wellnus/gamification/GamificationManager.java
  src/main/java/wellnus/gamification/util/GamificationData.java
  src/main/java/wellnus/gamification/util/GamificationStorage.java
  src/main/java/wellnus/gamification/util/GamificationTokenizer.java
  src/main/java/wellnus/storage/Storage.java
Labels: type.Story, priority.High

#272 Redirect logging to file
  src/main/java/wellnus/atomichabit/command/DeleteCommand.java
  src/main/java/wellnus/atomichabit/command/UpdateCommand.java
  src/main/java/wellnus/atomichabit/feature/AtomicHabitList.java
  src/main/java/wellnus/command/CommandParser.java
  src/main/java/wellnus/common/WellNusLogger.java
  src/main/java/wellnus/focus/command/ConfigCommand.java
  src/main/java/wellnus/focus/feature/FocusUi.java
  src/main/java/wellnus/reflection/command/FavoriteCommand.java
  src/main/java/wellnus/reflection/command/GetCommand.java
  src/main/java/wellnus/reflection/command/HomeCommand.java
  src/main/java/wellnus/reflection/command/LikeCommand.java
  src/main/java/wellnus/reflection/command/PrevCommand.java
  src/main/java/wellnus/reflection/command/UnlikeCommand.java
  src/main/java/wellnus/reflection/feature/QuestionList.java
  src/main/java/wellnus/reflection/feature/ReflectionManager.java
  src/main/java/wellnus/storage/ReflectionTokenizer.java
  src/main/java/wellnus/storage/Storage.java
  src/main/java/wellnus/ui/TextUi.java
Labels: type.Enhancement, priority.Medium

#280 Improve UserGuide
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#283 Improve FAQ section of UserGuide
  docs/UserGuide.md
Labels: type.Enhancement, priority.Low

#285 First draft of haoyangw's Project Portfolio Page
  docs/AboutUs.md
  docs/team/bernard.jpg
  docs/team/haoyangw.md
  docs/team/haoyangw.png
Labels: type.Task, priority.Medium

#286 Improve `gamif` `stats` command validation
  src/main/java/wellnus/gamification/command/StatsCommand.java
Labels: type.Bug, priority.Medium

#292 Improve Gamification Implementation
  src/main/java/wellnus/gamification/GamificationManager.java
  src/main/java/wellnus/gamification/command/HelpCommand.java
  src/main/java/wellnus/gamification/util/GamificationUi.java
  src/main/java/wellnus/ui/TextUi.java
Labels: type.Enhancement, priority.Low

#334 Fix AboutUs Page PPP URLs
  docs/AboutUs.md
Labels: type.Bug, severity.Medium

#293 Improve DeveloperGuide Formatting
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#340 Add gamification section to DeveloperGuide
  docs/DeveloperGuide.md
  docs/diagrams/GamificationClassDiagram.png
  docs/diagrams/GamificationClassDiagram.puml
  docs/diagrams/Manager.png
  docs/diagrams/Manager.puml
Labels: type.Task, priority.Medium

#335 Document wenxin ppp update
  docs/diagrams/ReflectionSequenceDiagram.png
  docs/diagrams/ReflectionSequenceDiagram.puml
  docs/team/wenxin-c.md
  docs/team/wenxin.md
Labels: type.Task, priority.Medium

#344 Cleaner logging
  src/main/java/wellnus/common/MainManager.java
  src/main/java/wellnus/common/WellNusLogger.java
Labels: type.Enhancement, priority.Medium

#343 Fix bogus Exception in GamificationTokenizer
  src/main/java/wellnus/common/MainManager.java
  src/main/java/wellnus/gamification/GamificationManager.java
  src/main/java/wellnus/gamification/util/GamificationData.java
  src/main/java/wellnus/gamification/util/GamificationStorage.java
  src/main/java/wellnus/storage/GamificationTokenizer.java
Labels: type.Bug, priority.Medium

#348 User guide improvements/fixes
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#353 `GamificationTokenizer` corrupt data file cleaning
  docs/diagrams/GamificationClassDiagram.png
  docs/diagrams/GamificationClassDiagram.puml
  src/main/java/wellnus/gamification/GamificationManager.java
  src/main/java/wellnus/gamification/util/GamificationStorage.java
  src/main/java/wellnus/gamification/util/GamificationUi.java
Labels: type.Bug, severity.Medium

#365 Cleanup code and UserGuide
  docs/UserGuide.md
  src/main/java/wellnus/common/MainManager.java
  src/main/java/wellnus/reflection/feature/QuestionList.java
Labels: type.Task, priority.Low

#367 Update contributions in haoyangw's PPP
  docs/team/haoyangw.md
Labels: type.Task, priority.High

#363 Write JUnit tests for `MainManager`
  src/main/java/wellnus/common/MainManager.java
  src/test/java/wellnus/common/MainManagerTest.java
Labels: type.Task, priority.High
