Repository AY2223S2-CS2113-T12-4/tp, pull requests merged in 2023-03, with the labels that each got.

#8 Fix text-ui-test bug
  build.gradle
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#10 Add aboutme for Nicholas
  docs/AboutUs.md
  docs/team/nichyjt.jpg
  docs/team/nichyjt.md
Labels: type.Task

#13 Protect repo with CODEOWNERS file
  docs/CODEOWNERS
Labels: type.Enhancement

#29 Define Command superclass
  src/main/java/seedu/duke/command/Command.java
Labels: type.Task, priority.High

#34 Fix parser off by one error
  src/main/java/seedu/duke/command/CommandParser.java
Labels: type.Bug, severity.Medium

#33 Add Manager class
  src/main/java/seedu/duke/manager/Manager.java
Labels: type.Task, priority.High

#31 Add atomic habits
  src/main/java/seedu/duke/WellNus.java
  src/main/java/seedu/duke/atomichabit/command/AddCommand.java
  src/main/java/seedu/duke/atomichabit/command/Command.java
  src/main/java/seedu/duke/atomichabit/command/CommandResult.java
  src/main/java/seedu/duke/atomichabit/command/ExitCommand.java
  src/main/java/seedu/duke/atomichabit/command/InvalidCommand.java
  src/main/java/seedu/duke/atomichabit/command/ListCommand.java
  src/main/java/seedu/duke/atomichabit/feature/AtomicHabit.java
  src/main/java/seedu/duke/atomichabit/feature/AtomicHabitList.java
  src/main/java/seedu/duke/atomichabit/feature/AtomicHabitManager.java
  src/main/java/seedu/duke/exception/AtomicHabitException.java
  src/test/java/seedu/duke/atomichabit/AtomicHabitTest.java
Labels: type.Story, priority.High

#46 Fix AboutUs picture rendering bug
  docs/AboutUs.md
Labels: type.Bug, severity.Low

#57 Add GitHub issue template for 'Enhancements' category
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/user-story-features.md
Labels: type.Enhancement, priority.Low

#70 Add defensive assertion checks to Manager
  src/main/java/wellnus/manager/Manager.java
Labels: type.Enhancement, priority.Low

#35 Feature self reflection
  src/main/java/wellnus/command/CommandParser.java
  src/main/java/wellnus/reflection/ExitCommand.java
  src/main/java/wellnus/reflection/GetCommand.java
  src/main/java/wellnus/reflection/ReflectUi.java
  src/main/java/wellnus/reflection/ReflectionManager.java
  src/main/java/wellnus/reflection/ReflectionQuestion.java
  src/main/java/wellnus/reflection/ReturnCommand.java
  src/main/java/wellnus/reflection/SelfReflection.java
  src/test/java/wellnus/reflection/GetCommandTest.java
  src/test/java/wellnus/reflection/ReflectionManagerTest.java
  src/test/java/wellnus/reflection/ReturnCommandTest.java
  src/test/java/wellnus/reflection/SelfReflectionTest.java
Labels: type.Story, priority.High

#71 Add assertions and logging to Command Parser
  src/main/java/wellnus/command/CommandParser.java
Labels: type.Enhancement, priority.Low

#30 Implement basic commands
  src/main/java/wellnus/command/ExitCommand.java
  src/main/java/wellnus/command/HelpCommand.java
  src/main/java/wellnus/common/MainManager.java
Labels: type.Story, priority.High

#72 Refactor atomic habits feature
  src/main/java/wellnus/atomichabit/command/AddCommand.java
  src/main/java/wellnus/atomichabit/command/Command.java
  src/main/java/wellnus/atomichabit/command/CommandResult.java
  src/main/java/wellnus/atomichabit/command/ExitCommand.java
  src/main/java/wellnus/atomichabit/command/InvalidCommand.java
  src/main/java/wellnus/atomichabit/command/ListCommand.java
  src/main/java/wellnus/atomichabit/command/UpdateCommand.java
  src/main/java/wellnus/atomichabit/feature/AtomicHabit.java
  src/main/java/wellnus/atomichabit/feature/AtomicHabitList.java
  src/main/java/wellnus/atomichabit/feature/AtomicHabitManager.java
  src/main/java/wellnus/command/Command.java
  src/main/java/wellnus/command/CommandParser.java
  src/main/java/wellnus/common/MainManager.java
  src/main/java/wellnus/ui/TextUi.java
  src/test/java/wellnus/atomichabit/AtomicHabitTest.java
Labels: type.Enhancement, priority.Medium

#81 Fix atomic habit commands
  src/main/java/wellnus/atomichabit/command/AddCommand.java
  src/main/java/wellnus/atomichabit/command/ExitCommand.java
  src/main/java/wellnus/atomichabit/command/ListCommand.java
  src/main/java/wellnus/atomichabit/command/UpdateCommand.java
  src/main/java/wellnus/atomichabit/feature/AtomicHabitManager.java
  src/test/java/wellnus/atomichabit/AtomicHabitTest.java
Labels: type.Bug, priority.Medium

#82 Support reflect commands
  src/main/java/wellnus/common/MainManager.java
  src/main/java/wellnus/reflection/ExitCommand.java
  src/main/java/wellnus/reflection/GetCommand.java
  src/main/java/wellnus/reflection/ReflectionManager.java
  src/main/java/wellnus/reflection/ReturnCommand.java
Labels: type.Task, priority.High

#86 Fix crash in GetCommand of reflections feature
  src/main/java/wellnus/reflection/GetCommand.java
  src/test/java/wellnus/reflection/GetCommandTest.java
Labels: type.Bug, priority.High

#87 Fix unintended BadCommandException
  src/main/java/wellnus/common/MainManager.java
Labels: type.Bug, priority.Medium

#90 Setup checkstyle for CS2113 coding style
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
  src/main/java/wellnus/WellNus.java
  src/main/java/wellnus/command/Command.java
  src/main/java/wellnus/command/CommandParser.java
  src/main/java/wellnus/command/ExitCommand.java
  src/main/java/wellnus/command/HelpCommand.java
Labels: type.Enhancement, priority.Low

#137 Define Tokenizer interface
  src/main/java/wellnus/exception/TokenizerException.java
  src/main/java/wellnus/storage/Tokenizer.java
Labels: type.Story, priority.High

#136 Remove obsolete method from Command classes
  src/main/java/wellnus/atomichabit/command/AddCommand.java
  src/main/java/wellnus/atomichabit/command/HomeCommand.java
  src/main/java/wellnus/atomichabit/command/ListCommand.java
  src/main/java/wellnus/atomichabit/command/UpdateCommand.java
  src/main/java/wellnus/command/Command.java
  src/main/java/wellnus/command/ExitCommand.java
  src/main/java/wellnus/command/HelpCommand.java
  src/main/java/wellnus/common/MainManager.java
  src/main/java/wellnus/reflection/GetCommand.java
  src/main/java/wellnus/reflection/HomeCommand.java
Labels: type.Enhancement, priority.Medium

#91 Setup gradle for building jar
  build.gradle
Labels: type.Task, priority.Low

#147 Update Tokenizer interface
  src/main/java/wellnus/storage/Tokenizer.java
Labels: type.Enhancement, priority.Medium

#144 Setup developer guide skeleton
  docs/DeveloperGuide.md
  docs/diagrams/style.puml
Labels: type.Task, priority.High

#153 Reflection developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ReflectionClassDiagram.png
  docs/diagrams/ReflectionClassDiagram.puml
  docs/diagrams/style.puml
Labels: type.Task, priority.High

#158 Update DeveloperGuide for Managers Implementation
  docs/DeveloperGuide.md
  docs/diagrams/managers.png
  docs/diagrams/managers.puml
Labels: type.Task, priority.Medium

#123 [UpdateCommand] Switch from Exception to assertion
  src/main/java/wellnus/atomichabit/command/UpdateCommand.java
Labels: type.Enhancement, priority.Low

#169 Add `config` and restart logic for `FocusTimer`
  src/main/java/wellnus/exception/FocusException.java
  src/main/java/wellnus/focus/command/CheckCommand.java
  src/main/java/wellnus/focus/command/ConfigCommand.java
  src/main/java/wellnus/focus/command/HomeCommand.java
  src/main/java/wellnus/focus/command/NextCommand.java
  src/main/java/wellnus/focus/command/PauseCommand.java
  src/main/java/wellnus/focus/command/ResumeCommand.java
  src/main/java/wellnus/focus/command/StartCommand.java
  src/main/java/wellnus/focus/command/StopCommand.java
  src/main/java/wellnus/focus/feature/Countdown.java
  src/main/java/wellnus/focus/feature/FocusManager.java
  src/main/java/wellnus/focus/feature/Session.java
  src/test/java/wellnus/focus/FocusTest.java
  src/test/java/wellnus/focus/command/ConfigCommandTest.java
Labels: priority.High

#184 Update DeveloperGuide to include gamification feature
  docs/DeveloperGuide.md
  docs/diagrams/Manager.png
  docs/diagrams/Manager.puml
  docs/diagrams/WellnusSequence.png
  docs/diagrams/WellnusSequence.puml
Labels: type.Task, priority.Medium

#178 Basic implementation of gamification feature
  src/main/java/wellnus/atomichabit/command/UpdateCommand.java
  src/main/java/wellnus/atomichabit/feature/AtomicHabitManager.java
  src/main/java/wellnus/command/Command.java
  src/main/java/wellnus/command/HelpCommand.java
  src/main/java/wellnus/common/MainManager.java
  src/main/java/wellnus/exception/GamificationException.java
  src/main/java/wellnus/gamification/GamificationManager.java
  src/main/java/wellnus/gamification/command/HomeCommand.java
  src/main/java/wellnus/gamification/command/StatsCommand.java
  src/main/java/wellnus/gamification/util/GamificationData.java
  src/main/java/wellnus/gamification/util/GamificationUi.java
  src/main/java/wellnus/manager/Manager.java
  src/test/java/wellnus/atomichabit/AtomicHabitTest.java
Labels: type.Epic, priority.Medium

#203 Fix unreliable home commands
  src/main/java/wellnus/atomichabit/command/HomeCommand.java
  src/main/java/wellnus/focus/command/HomeCommand.java
  src/main/java/wellnus/gamification/GamificationManager.java
  src/main/java/wellnus/gamification/command/HomeCommand.java
  src/main/java/wellnus/reflection/command/HomeCommand.java
Labels: type.Bug, priority.High

#200 Gamification user guide
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#207 Fix bogus Tokenizer Exceptions
  src/main/java/wellnus/reflection/feature/QuestionList.java
  src/main/java/wellnus/storage/AtomicHabitTokenizer.java
  src/main/java/wellnus/storage/ReflectionTokenizer.java
Labels: type.Enhancement, priority.Medium

#209 User Guide improvements
  docs/UserGuide.md
Labels: type.Task, priority.Medium
